# Generated by Django 4.2.6 on 2024-04-20 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Customer', '0010_alter_supply_today_bottle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bill_number', models.CharField(blank=True, max_length=200)),
                ('bill_date', models.DateField()),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('details', models.CharField(blank=True, max_length=200)),
                ('bottle_couont', models.IntegerField(blank=True)),
                ('rate', models.FloatField()),
                ('count_total', models.FloatField()),
                ('baaki_jamaa', models.FloatField()),
                ('final_price', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Customer.customers')),
            ],
        ),
    ]
