# Generated by Django 4.2.6 on 2024-04-24 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='bill_date',
            field=models.DateField(auto_now=True),
        ),
    ]
