# Generated by Django 4.2.6 on 2024-04-24 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billing', '0002_alter_bills_bill_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bills',
            name='updated_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
