# Generated by Django 4.2.6 on 2023-10-24 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
        ('Customer', '0002_alter_customers_area_alter_customers_c_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Landmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landmark', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customers',
            name='Updated_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Customer_products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.customers')),
                ('Customers_product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Product.product')),
            ],
        ),
        migrations.AddField(
            model_name='customers',
            name='Landmark',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Customer.landmark'),
        ),
    ]
