# Generated by Django 4.2.6 on 2023-10-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0003_landmark_alter_customers_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='Reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
