# Generated by Django 4.2.6 on 2023-10-25 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0004_customers_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='Current_status',
            field=models.CharField(blank=True, default='1', max_length=20, null=True),
        ),
    ]
