# Generated by Django 4.2.6 on 2023-10-26 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0005_alter_customers_current_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Close_customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(blank=True, null=True)),
                ('Reason', models.TextField(blank=True, null=True)),
                ('Customers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.customers')),
            ],
        ),
    ]
