# Generated by Django 4.2.6 on 2023-10-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0006_close_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='is_deleted',
            field=models.BooleanField(blank=True, default='0', null=True),
        ),
    ]
