# Generated by Django 4.2.6 on 2023-11-05 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0007_alter_customers_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='User_delevery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_created=True)),
                ('Date', models.DateField(blank=True, null=True)),
                ('milk_need', models.IntegerField(blank=True, null=True)),
                ('Customers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.customers')),
            ],
        ),
    ]
