# Generated by Django 4.2.6 on 2023-11-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0008_alter_customers_is_deleted_user_delevery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_delevery',
            name='created_at',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
