# Generated by Django 4.2.6 on 2023-12-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0009_alter_user_delevery_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='Today_bottle',
            field=models.FloatField(),
        ),
    ]
