# Generated by Django 4.2.6 on 2024-05-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0010_alter_supply_today_bottle'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='Restarted_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
