# Generated by Django 4.2.6 on 2023-10-14 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=100)),
                ('Hsn_code', models.CharField(blank=True, max_length=20, null=True)),
                ('Product_unit', models.CharField(blank=True, max_length=20, null=True)),
                ('Product_price', models.CharField(blank=True, max_length=20, null=True)),
                ('Previous_stock', models.CharField(blank=True, max_length=20, null=True)),
                ('Minimum_stock', models.CharField(blank=True, max_length=20, null=True)),
                ('Maximum_stock', models.CharField(blank=True, max_length=20, null=True)),
                ('Product_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('Updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
