# Generated by Django 4.2.6 on 2023-10-14 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery_boy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=50)),
                ('Name', models.CharField(max_length=50)),
                ('Group', models.CharField(blank=True, max_length=50, null=True)),
                ('Home_number', models.CharField(blank=True, max_length=150, null=True)),
                ('Society', models.CharField(blank=True, max_length=150, null=True)),
                ('Area', models.CharField(blank=True, max_length=150, null=True)),
                ('Pincode', models.CharField(blank=True, max_length=50, null=True)),
                ('Moblie1', models.CharField(blank=True, max_length=20, null=True)),
                ('Moblie2', models.CharField(blank=True, max_length=20, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('License_number', models.CharField(blank=True, max_length=50, null=True)),
                ('License_lastdate', models.DateField(blank=True, null=True)),
                ('License_type', models.CharField(blank=True, max_length=50, null=True)),
                ('Birth_date', models.CharField(blank=True, max_length=50, null=True)),
                ('Joining_date', models.DateField(blank=True, null=True)),
                ('Current_status', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('Updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
