# Generated by Django 4.2.6 on 2023-12-31 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery_boy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery_boy',
            name='Email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
