# Generated by Django 4.2.6 on 2023-10-14 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Vehicles', '0001_initial'),
        ('Delivery_boy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Route_name', models.CharField(max_length=150)),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('Delivery_boy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Delivery_boy.delivery_boy')),
                ('Vehicle_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vehicles.vehicle')),
            ],
        ),
    ]
