# Generated by Django 5.1.5 on 2025-01-18 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0011_customers_restarted_date'),
        ('Trip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='Customer_list',
            field=models.ManyToManyField(blank=True, to='Customer.customers'),
        ),
    ]
